# Generated by Django 3.1.7 on 2021-06-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 21, 51, 336118)),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='Telephone',
            field=models.CharField(max_length=50),
        ),
    ]
