# Generated by Django 3.2.4 on 2021-06-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_auto_20210615_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentinfo',
            name='AppointmentID',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
