# Generated by Django 3.1.7 on 2021-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20210617_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('User_Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
